local function load()
	if SERVER then
		RunConsoleCommand("sv_allowcslua", "1")
		util.AddNetworkString("UpdateLocalEnvironment")
		AddCSLuaFile("autorun/loader.lua")
		AddCSLuaFile("core/shared/environment.lua")
		AddCSLuaFile("core/shared/slot.lua")
		AddCSLuaFile("core/shared/core.lua")
		AddCSLuaFile("core/client/core.lua")
		AddCSLuaFile("core/shared/plugins.lua")
		AddCSLuaFile("core/shared/space.lua")
		AddCSLuaFile("core/shared/util.lua")
		AddCSLuaFile("core/shared/plug.lua")
		AddCSLuaFile("core/shared/pipe.lua")
		AddCSLuaFile("core/shared/devices.lua")
		include("core/shared/util.lua")
		include("core/shared/environment.lua")
		include("core/server/universe.lua")
		include("core/shared/plug.lua")
		include("core/shared/slot.lua")
		include("core/shared/pipe.lua")
		include("core/server/core.lua")
		include("core/shared/core.lua")
		include("core/server/initializer.lua")
		include("core/shared/plugins.lua")
		include("core/shared/space.lua")
		include("core/server/resources.lua")
		include("core/shared/devices.lua")
	elseif CLIENT then
		include("core/shared/util.lua")
		include("core/shared/environment.lua")
		include("core/shared/plug.lua")
		include("core/shared/slot.lua")
		include("core/shared/pipe.lua")
		include("core/client/core.lua")
		include("core/shared/core.lua")
		include("core/shared/plugins.lua")
		include("core/shared/environment.lua")
		include("core/shared/space.lua")
		include("core/shared/devices.lua")
		end
	print("Gamemode loaded !")
end
 if ( string.find( string.lower( game.GetMap() ), "sb_" ) ) then load() end
concommand.Add("gmreload", load)